name: Linux build example
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      AUTOBUILD_ADDRSIZE: 64
      AUTOBUILD_VARIABLES_FILE: ${{ github.workspace }}/.fs-build-variables/variables
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout build variables
        uses: actions/checkout@v4
        with:
          repository: FirestormViewer/fs-build-variables
          path: .fs-build-variables

      - name: Checkout master-message-template
        uses: actions/checkout@v4
        with:
          repository: secondlife/master-message-template
          path: .master-message-template

      - name: Install autobuild and python dependencies
        run: pip3 install autobuild llsd llbase

      - name: Install Linux dependencies
        if: runner.os == 'linux'
        run: sudo apt update && sudo apt install -y libgl1-mesa-dev libglu1-mesa-dev libpulse-dev build-essential git libssl-dev libxinerama-dev libxrandr-dev libfontconfig-dev libfreetype6-dev ninja-build

      - name: Build
        id: build
        shell: bash
        run: |
          autobuild configure -A 64 -c ReleaseFS_open -- --no-opensim --avx2 --tracy --ninja --vscode
          cd build-linux-x86_64 && ninja -k0
